# Generated by Django 5.2.3 on 2025-06-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_fitnessclass_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
    ]
