# Generated by Django 5.2.3 on 2025-06-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_booking_client_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
