# Generated by Django 5.2.3 on 2025-06-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('client_name', 'class_instance')},
        ),
    ]
